name: lint

on:
  push:
    branches: [ ready ]
  pull_request:
    branches: [ ready ]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@3.5
        with:
          cli: 1.10.3.986
      
      - name: Setup clj-kondo
        uses: DeLaGuardo/setup-clj-kondo@master
        with: 
          version: '2021.12.19'
      
      - name: Lint
        run: ./scripts/lint.sh
